# Generated by Django 6.0.6 on 2026-06-22 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=200, verbose_name='Назва (UA)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('event_type', models.CharField(choices=[('regular', 'Звичайний івент'), ('community', 'Community івент')], default='regular', max_length=20, verbose_name='Тип івенту')),
                ('date', models.DateTimeField(verbose_name='Дата та час')),
                ('venue_ua', models.CharField(max_length=300, verbose_name='Місце (UA)')),
                ('venue_en', models.CharField(max_length=300, verbose_name='Venue (EN)')),
                ('description_ua', models.TextField(verbose_name='Опис (UA)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='Обкладинка')),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ціна квитка (€)')),
                ('ticket_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ліміт місць')),
                ('ticket_url', models.URLField(blank=True, verbose_name='Посилання на квитки')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Івент',
                'verbose_name_plural': 'Івенти',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='events/gallery/', verbose_name='Фото (завантажити)')),
                ('external_url', models.URLField(blank=True, verbose_name='Посилання на фото (Google Drive тощо)')),
                ('caption_ua', models.CharField(blank=True, max_length=300, verbose_name='Підпис (UA)')),
                ('caption_en', models.CharField(blank=True, max_length=300, verbose_name='Caption (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events.event', verbose_name='Івент')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Фото галереї',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
