# Generated by Django 6.0.6 on 2026-06-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_album_url',
            field=models.URLField(blank=True, verbose_name='Посилання на фотоальбом (Google Drive)'),
        ),
    ]
