# Generated by Django 6.0.6 on 2026-06-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_photo_album_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo_album_url',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='external_url',
        ),
    ]
