# Generated by Django 6.0.6 on 2026-06-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_photo_album_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['created_at'], 'verbose_name': 'Фото галереї', 'verbose_name_plural': 'Фото галереї'},
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='caption_en',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='caption_ua',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='order',
        ),
        migrations.AddField(
            model_name='event',
            name='photo_album_url',
            field=models.URLField(blank=True, verbose_name='Посилання на фотоальбом (Google Drive)'),
        ),
    ]
