# Generated by Django 6.0.6 on 2026-07-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_category_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
    ]
