# Generated by Django 6.0.6 on 2026-07-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Short description (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ua',
            field=models.CharField(blank=True, max_length=160, verbose_name='Короткий опис (UA)'),
        ),
    ]
