# Generated by Django 6.0.6 on 2026-07-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_richer_category_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата та час'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Опубліковано'),
        ),
    ]
