# Generated by Django 6.0.6 on 2026-06-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ua', models.CharField(max_length=300, verbose_name='Питання (UA)')),
                ('answer_ua', models.TextField(verbose_name='Відповідь (UA)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description_ua', models.CharField(blank=True, max_length=300, verbose_name='Опис (UA)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнери',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ua', models.CharField(max_length=100, verbose_name='Назва (UA)')),
                ('price_from', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Ціна від (€)')),
                ('price_to', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Ціна до (€)')),
                ('guests_ua', models.CharField(max_length=100, verbose_name='Гості (UA)')),
                ('features_ua', models.TextField(help_text='Кожен пункт з нового рядка', verbose_name='Що входить (UA)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Виділений (зірочка)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Пакет прайсу',
                'verbose_name_plural': 'Пакети прайсу',
                'ordering': ['order'],
            },
        ),
    ]
