# Generated by Django 6.0.6 on 2026-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_galleryitem_options_and_more'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='Заповнюйте лише якщо не увімкнено "Показувати на всіх івентах"', related_name='faqs', to='events.event', verbose_name='Або оберіть конкретні івенти'),
        ),
        migrations.AddField(
            model_name='faq',
            name='show_on_all_events',
            field=models.BooleanField(default=False, verbose_name='Показувати на всіх івентах'),
        ),
    ]
