# Generated by Django 6.0.6 on 2026-07-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_faq_events_faq_show_on_all_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='Answer (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Question (EN)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='pricepackage',
            name='features_en',
            field=models.TextField(blank=True, help_text='Each item on a new line', verbose_name='Features (EN)'),
        ),
        migrations.AddField(
            model_name='pricepackage',
            name='guests_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Guests (EN)'),
        ),
        migrations.AddField(
            model_name='pricepackage',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (EN)'),
        ),
    ]
