# Generated by Django 6.0.6 on 2026-07-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_faq_answer_en_faq_question_en_partner_description_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricePackage',
        ),
    ]
