# Generated by Django 6.0.6 on 2026-07-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_pricepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
    ]
