# Generated by Django 6.0.6 on 2026-07-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_partner_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
    ]
