# Generated by Django 6.0.6 on 2026-06-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Імʼя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон / Telegram')),
                ('event_type', models.CharField(blank=True, max_length=200, verbose_name='Тип івенту')),
                ('guests', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість гостей')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Бюджет')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В обробці'), ('confirmed', 'Підтверджена'), ('rejected', 'Відхилена')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка на бронювання',
                'verbose_name_plural': 'Заявки на бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
