# Generated by Django 6.0.6 on 2026-06-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
    ]
