# Generated by Django 6.0.6 on 2026-07-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingrequest_telegram_alter_bookingrequest_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Імʼя / компанія')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('partnership_type', models.CharField(blank=True, choices=[('location', 'Локація'), ('sponsor', 'Бренд / спонсор'), ('artist', 'Артист / MC'), ('other', 'Інше')], max_length=20, verbose_name='Тип співпраці')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В обробці'), ('confirmed', 'Підтверджена'), ('rejected', 'Відхилена')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заявка на партнерство',
                'verbose_name_plural': 'Заявки на партнерство',
                'ordering': ['-created_at'],
            },
        ),
    ]
