# Generated by Django 6.0.6 on 2026-07-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_partnershiprequest'),
        ('events', '0006_remove_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='event_type',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Бюджет'),
        ),
    ]
