# Generated by Django 6.0.6 on 2026-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_bookingrequest_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Імʼя'),
        ),
    ]
